# this uses docker python images (based on Debian)
version: 2
jobs:
  build:
    # working_directory: ~/playground
    docker:
      - image: circleci/python:3.7.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: sudo chown circleci:circleci /usr/local/bin /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "src/Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            cd ~/project/src
            export PIPENV_VENV_IN_PROJECT=enabled
            pipenv install
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "src/Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          command: |
            cd ~/project/src && ./run-tests.sh
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
